import { MenuItem } from '../types';

export const MENU_ITEMS: MenuItem[] = [
  {
    id: 'wagyu-chow-fun',
    name: 'Wok-Flared Wagyu Chow Fun',
    chineseName: '黑松露和牛炒河粉',
    description: 'Aged pasture Wagyu beef, fresh flat rice noodles charred at 320°C with shaved winter black truffles.',
    price: '¥188',
    prepTimeSeconds: 210,
    calories: 780,
    spicyLevel: 1,
    imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'szechuan-brisket',
    name: 'Szechuan Smoked Brisket Wok',
    chineseName: '夜間川味煙燻牛胸',
    description: 'Premium product drop. Grain-fed Angus brisket seared at 320°C with custom volcanic spice.',
    price: '¥260',
    prepTimeSeconds: 240,
    calories: 920,
    spicyLevel: 3,
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'truffle-dumplings',
    name: 'Truffle Chiang Mai Dumplings',
    chineseName: '金箔香露松露蒸餃',
    description: 'Fresh organic beet wrapper loaded with dry-aged heritage pork and rich winter black truffle glaze.',
    price: '¥165',
    prepTimeSeconds: 180,
    calories: 420,
    spicyLevel: 0,
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'lotus-chips',
    name: 'Crispy Lotus Root Chips',
    chineseName: '香脆七彩蓮藕片',
    description: 'Crispy thinly sliced organic lotus roots with dried Szechuan pepper hull and pure volcanic salt dust.',
    price: '¥82',
    prepTimeSeconds: 90,
    calories: 140,
    spicyLevel: 1,
    imageUrl: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'lotus-dimsum',
    name: 'Electric Lotus Caviar Dumplings',
    chineseName: '粉蓮魚子醬蒸饺',
    description: 'Electric-pink beet wrapper, dry-aged heritage pork, luxury golden caviar, and scallion nectar.',
    price: '¥145',
    prepTimeSeconds: 180,
    calories: 420,
    spicyLevel: 0,
    imageUrl: 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'szechuan-duck-roll',
    name: 'Fuel-Injected Szechuan Duck Roll',
    chineseName: '噴射川味烤鴨卷',
    description: 'Crispy maple leaf duck, fuel-injected spicy broad bean glaze, wrapped in a house-milled flour crepe.',
    price: '¥120',
    prepTimeSeconds: 150,
    calories: 590,
    spicyLevel: 3,
    imageUrl: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'nitro-jasmine',
    name: 'Crimson Jasmine Nitro Cold Brew',
    chineseName: '氮氣紅茉莉冷萃茶',
    description: 'Cold-steeped organic Jasmine tea infused with nitrogen gas pressure for a velvety, micro-foamed finish.',
    price: '¥65',
    prepTimeSeconds: 60,
    calories: 12,
    spicyLevel: 0,
    imageUrl: 'https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=800&q=80',
  },
];
